events{

}

# yaha server ke bare m batate hai
http{

  upstream backend{
    server server1:7000;
    server server2:7000;
    server server3:7000;
  }
  server{
    # server kaha listen ho raha hai
    listen 80;
    # agar web server ki tarha use kare nginx ko to use karte hai
    # location /{
    #   return 200 "hello from nginx";
    # }

    # As a load balancer
    location /{
      proxy_pass http://backend;
    }
  }
}